CREATE TABLE CLIENTE(
    IdCliente INTEGER PRIMARY KEY NOT NULL,
    Nome VARCHAR2(255) NOT NULL,
    Celular VARCHAR2(9) NULL,
    UF CHAR(2) NULL
);

COMMIT;

CREATE TABLE TIPO_FINANCIAMENTO(
    IdTipoFinancimento INTEGER PRIMARY KEY NOT NULL,
    Nome VARCHAR2(255)
);

COMMIT;

CREATE TABLE FINANCIAMENTO(
    IdFinanciamento INTEGER PRIMARY KEY NOT NULL,
    IdCliente INTEGER NOT NULL,
    IdTipoFinancimento INTEGER NULL,
    ValorTotal NUMBER(10,2) NOT NULL,
    DataVencimento DATE NOT NULL
);

COMMIT;

ALTER TABLE FINANCIAMENTO ADD CONSTRAINTS ID_CLIENTE_FK FOREIGN KEY(IdCliente) references CLIENTE(IdCliente);

COMMIT;

ALTER TABLE FINANCIAMENTO ADD CONSTRAINTS ID_TIPO_FINANCIAMENTO_FK FOREIGN KEY(IdTipoFinancimento) references TIPO_FINANCIAMENTO(IdTipoFinancimento);

COMMIT;

CREATE TABLE PARCELA(
    IdParcela INTEGER PRIMARY KEY NOT NULL,
    IdFinanciamento INTEGER NOT NULL,
    NumeroParcela INTEGER NOT NULL,
    ValorParcela NUMBER(10,2) NOT NULL,
    DataVencimento DATE NOT NULL,
    DataPagamento DATE NULL
);

COMMIT;

ALTER TABLE PARCELA ADD CONSTRAINTS ID_FINANCIAMENTO_FK FOREIGN KEY(IdFinanciamento) references FINANCIAMENTO(IdFinanciamento);

COMMIT;




