SELECT 
    NOME, 
    (PERCENTUAL_PARCELAS_PAGAS || '%') AS PERCENTUAL_PARCELAS_PAGAS
FROM(
    SELECT 
        CLIENTE.NOME, 
        (COUNT(PARCELA.IDPARCELA) /
        ( 
            SELECT 
                COUNT(DISTINCT CLIENTE.IDCLIENTE) AS QTDP_CLIENTES
            FROM CLIENTE
            INNER JOIN FINANCIAMENTO ON CLIENTE.IDCLIENTE = FINANCIAMENTO.IDCLIENTE
            INNER JOIN PARCELA ON FINANCIAMENTO.IDFINANCIAMENTO = PARCELA.IDFINANCIAMENTO
            WHERE CLIENTE.UF = 'SP'
            AND PARCELA.DATAPAGAMENTO IS NOT NULL
        )* 100) AS PERCENTUAL_PARCELAS_PAGAS
    FROM CLIENTE
    INNER JOIN FINANCIAMENTO ON CLIENTE.IDCLIENTE = FINANCIAMENTO.IDCLIENTE
    INNER JOIN PARCELA ON FINANCIAMENTO.IDFINANCIAMENTO = PARCELA.IDFINANCIAMENTO
    WHERE CLIENTE.UF = 'SP'
    AND PARCELA.DATAPAGAMENTO IS NOT NULL
    GROUP BY CLIENTE.NOME
) TB
WHERE TB.PERCENTUAL_PARCELAS_PAGAS > 60;
