SELECT 
    NOME
FROM (
SELECT 
    CLIENTE.NOME
FROM CLIENTE
 INNER JOIN FINANCIAMENTO ON CLIENTE.IDCLIENTE = FINANCIAMENTO.IDCLIENTE
 INNER JOIN PARCELA ON FINANCIAMENTO.IDFINANCIAMENTO = PARCELA.IDFINANCIAMENTO
WHERE PARCELA.DATAVENCIMENTO > (SYSDATE + 5)
 AND PARCELA.DATAPAGAMENTO IS NULL
GROUP BY CLIENTE.NOME
)
WHERE ROWNUM <= 4;