SELECT 
    CLIENTE.NOME
FROM CLIENTE
 INNER JOIN FINANCIAMENTO ON CLIENTE.IDCLIENTE = FINANCIAMENTO.IDCLIENTE
 INNER JOIN PARCELA ON FINANCIAMENTO.IDFINANCIAMENTO = PARCELA.IDFINANCIAMENTO
WHERE PARCELA.DATAPAGAMENTO IS NOT NULL
AND (PARCELA.DATAPAGAMENTO - PARCELA.DATAVENCIMENTO) > 10
AND FINANCIAMENTO.VALORTOTAL > 10000.00
GROUP BY CLIENTE.NOME
HAVING COUNT(PARCELA.IDPARCELA) >= 2;